### ISSUE TITLE
Spacing errors

### ISSUE THREAD

**Issue by upenha** [huozhi/sugar-high#124]
![Image](https://github.com/user-attachments/assets/88f354b2-4baa-46b7-ab57-8783a0220812)

I dont know why but my codeblock keeps with that big space, i'm using sugar-high latest version (0.9.2) and my code looks like that: 

```tsx
function Code({ children, ...props }: any) {
  let codeHTML = highlight(children);
  return <code dangerouslySetInnerHTML={{ __html: codeHTML }} {...props} />;
}
```

and thats my css code for customizing that code block:
```css
p>code,
p>pre {
  @apply relative px-2 whitespace-nowrap;
}

p>pre::before,
p>code::before {
  @apply absolute inset-x-0 -inset-y-1 bg-neutral-500/10 border border-neutral-200 dark:border-neutral-800/60 rounded-md -z-10;
  content: '';
}

p>pre,
p>code {
  @apply text-neutral-800 dark:text-neutral-200;
}


.prose :where(code):not(:where([class~='not-prose'], [class~='not-prose'] *))::before,
.prose :where(code):not(:where([class~='not-prose'], [class~='not-prose'] *))::after {
  content: '';
}

p>pre span,
p>code span {
  color: inherit !important;
}


.prose pre {
  @apply border bg-neutral-100 border-neutral-200 dark:bg-neutral-900/40 dark:border-neutral-800 rounded-md p-4 overflow-x-auto;
}
```

**Comment by upenha** [comment]
ok im pretty dumb i guess, i forgot to create a css thingy for making the .sh__line inline-flex

```css
code .sh__line {
  display: inline-flex;
}
```
im leaving this "snippet" here in case someone needs help w that
